### GENERAL SETTINGS ###

# Site settings
title: "PAUL STAAB"
description: "Personal Homepage of Paul Staab"
analytics: UA-86675232-1
baseurl: "/." #important: start with /
url: "http://paulstaab.de"
wallpaper: summer2.jpg

navigation:
  - title: HOME
    url: /
  - title: PROJECTS
    url: /projects/
#  - title: PHOTOS
#    url: /photos/
  - title: SCIENCE
    url: /science/

collections:
  projects:
    output: true
  publications:
    output: false

# Build settings
markdown: kramdown
permalink: /:year/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/paulstaab
  - title: twitter
    url: https://twitter.com/paulstaab 
  - title: linkedin
    url: https://de.linkedin.com/in/paulstaab
  - title: facebook
    url: https://www.facebook.com/paul.r.staab
    
about: "I'm a Data Scientist and R Package Developer in Munich, Germany."

