### GENERAL SETTINGS ###

# Site settings
title: "PAUL STAAB"
description: "Personal Homepage of Paul Staab"
analytics:
baseurl: "/." #important: start with /
url: "https://paulstaab.de"
wallpaper: spring1.jpg

blog:
  title: "Blog"
  description: ""
  url: "https://paulstaab.de/blog/index.html"

navigation:
  - title: HOME
    url: /
  #- title: BLOG
  #  url: /blog/index.html
  # - title: INVESTMENTS
  #  url: /investments.html
  #- title: PROJECTS
  #  url: /projects.html
  #- title: SCIENCE
  #  url: /science.html

collections:
  projects:
    output: false
  publications:
    output: false

# Build settings
markdown: kramdown
permalink: /blog/:year/:title.html
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
sass:
  style: compressed

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#FFFFFF" # "#384452" #"#33004D"
  text: "#000000"
  text_menu: "#2a2f36"
  link: "#428bca"
  link_hover: "#01b2fe"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Shown in footer.
social:
  - title: github
    url: https://github.com/paulstaab
  - title: twitter
    url: https://twitter.com/paulstaab
  - title: linkedin
    url: https://de.linkedin.com/in/paulstaab
    
about: "I'm a ML Engineer in Munich, Germany."
plugins:
  - jekyll-sitemap

