name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
    - uses: actions/upload-artifact@v1
      with:
        name: homepage
        path: _site

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: homepage
        path: .
    
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.4
      with:
        root: .

    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r .
  
